//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Bookie.Common.Resources.Strings {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Bookie.Common.Resources.Strings.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to scan this source now?.
        /// </summary>
        public static string DoYouWantToScanResource {
            get {
                return ResourceManager.GetString("DoYouWantToScanResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while determining if the Author exists.
        /// </summary>
        public static string Error_AuthorExists {
            get {
                return ResourceManager.GetString("Error_AuthorExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while deleting the Author.
        /// </summary>
        public static string Error_DeletingAuthor {
            get {
                return ResourceManager.GetString("Error_DeletingAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while deleting the Publisher.
        /// </summary>
        public static string Error_DeletingPublisher {
            get {
                return ResourceManager.GetString("Error_DeletingPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while deleting the Source Directory.
        /// </summary>
        public static string Error_DeletingSourceDirectory {
            get {
                return ResourceManager.GetString("Error_DeletingSourceDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while retrieving all Authors.
        /// </summary>
        public static string Error_GetAllAuthors {
            get {
                return ResourceManager.GetString("Error_GetAllAuthors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while retrieving all Books.
        /// </summary>
        public static string Error_GetAllBooks {
            get {
                return ResourceManager.GetString("Error_GetAllBooks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while retrieving all Publishers.
        /// </summary>
        public static string Error_GetAllPublishers {
            get {
                return ResourceManager.GetString("Error_GetAllPublishers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while retrieving all Source Directories.
        /// </summary>
        public static string Error_GetAllSourceDirectories {
            get {
                return ResourceManager.GetString("Error_GetAllSourceDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while retrieving the Author.
        /// </summary>
        public static string Error_GetAuthorById {
            get {
                return ResourceManager.GetString("Error_GetAuthorById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while retrieving the Publisher.
        /// </summary>
        public static string Error_GetPublisherById {
            get {
                return ResourceManager.GetString("Error_GetPublisherById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while retrieving the Source Directory.
        /// </summary>
        public static string Error_GetSourceDirectoryById {
            get {
                return ResourceManager.GetString("Error_GetSourceDirectoryById", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while inserting the Author.
        /// </summary>
        public static string Error_InsertingAuthor {
            get {
                return ResourceManager.GetString("Error_InsertingAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while inserting the Publisher.
        /// </summary>
        public static string Error_InsertingPublisher {
            get {
                return ResourceManager.GetString("Error_InsertingPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while inserting the Source Directory.
        /// </summary>
        public static string Error_InsertingSourceDirectory {
            get {
                return ResourceManager.GetString("Error_InsertingSourceDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while determining if the Publisher exists.
        /// </summary>
        public static string Error_PublisherExists {
            get {
                return ResourceManager.GetString("Error_PublisherExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured while determining if the Source Directory exists.
        /// </summary>
        public static string Error_SourceDirectoryExists {
            get {
                return ResourceManager.GetString("Error_SourceDirectoryExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while updating the Author.
        /// </summary>
        public static string Error_UpdatingAuthor {
            get {
                return ResourceManager.GetString("Error_UpdatingAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while updating the Publisher.
        /// </summary>
        public static string Error_UpdatingPublisher {
            get {
                return ResourceManager.GetString("Error_UpdatingPublisher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while updating the Source Directory.
        /// </summary>
        public static string Error_UpdatingSourceDirectory {
            get {
                return ResourceManager.GetString("Error_UpdatingSourceDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Source Directory already exists.
        /// </summary>
        public static string Message_SourceDirectoryExists {
            get {
                return ResourceManager.GetString("Message_SourceDirectoryExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string TopMenu_About {
            get {
                return ResourceManager.GetString("TopMenu_About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string TopMenu_Exit {
            get {
                return ResourceManager.GetString("TopMenu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string TopMenu_File {
            get {
                return ResourceManager.GetString("TopMenu_File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Log.
        /// </summary>
        public static string TopMenu_ViewLog {
            get {
                return ResourceManager.GetString("TopMenu_ViewLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An unexpected error has occurred.
        /// </summary>
        public static string UnhandledException {
            get {
                return ResourceManager.GetString("UnhandledException", resourceCulture);
            }
        }
    }
}
